<script setup>
import { onMounted, ref } from 'vue'
import { getJson } from './api'
const programs=ref([]), loading=ref(true), error=ref(''), expanded=ref(null)
async function load(){loading.value=true;error.value='';try{programs.value=await getJson('/api/programs')}catch{error.value='We couldn’t load the programs. Please try again, or get in touch on Instagram.'}finally{loading.value=false}}
onMounted(load)
</script>
<template>
<section class="program-heading"><div class="eyebrow"><span class="dot"></span> YOUR NEXT CHAPTER</div><div class="program-title"><h1>Your goals.<br><em>Your way forward.</em></h1><p>From a little structure to personal support.<br>Find the approach that fits your life.</p></div></section>
<section class="program-section" aria-label="Programs and mentorship"><p class="draft-note">Explore possible training options. Details and availability are confirmed directly with Arizona Lifts.</p><div v-if="loading" class="status" role="status">Loading programs…</div><div v-else-if="error" class="status" role="alert"><p>{{ error }}</p><button class="button primary" @click="load">Try again ↻</button></div><p v-else-if="!programs.length" class="status">New programs are on the way. Get in touch on Instagram to learn more.</p><div v-else class="program-grid"><article v-for="(program,index) in programs" :key="program.id" class="program-card" :class="{featured:program.featured}"><div class="card-top"><span>0{{index+1}} / {{program.category}}</span><span>{{program.symbol}}</span></div><div class="card-body"><span class="pill">{{program.label}}</span><h2>{{program.name}}</h2><p>{{program.description}}</p><ul><li v-for="feature in program.features" :key="feature"><span>↗</span>{{feature}}</li></ul><button class="detail-toggle" :aria-expanded="expanded===program.id" :aria-controls="`details-${program.id}`" @click="expanded=expanded===program.id?null:program.id">Who is this for? <span>{{expanded===program.id?'−':'+'}}</span></button><p v-if="expanded===program.id" :id="`details-${program.id}`" class="detail">{{program.suitedFor}}</p><a class="button" :class="program.featured?'primary':'outline'" href="https://www.instagram.com/arizonalifts/" target="_blank" rel="noopener noreferrer">Ask about this program <span>↗</span></a></div></article></div></section>
<section class="contact-strip"><div><span class="eyebrow">LET’S FIND YOUR FIT</span><h2>Not sure where to start?</h2><p>Share your goals and find your next step together.</p></div><a class="button primary" href="https://www.instagram.com/arizonalifts/" target="_blank" rel="noopener noreferrer">Let’s talk on Instagram <span>↗</span></a></section>
</template>
